"""Ports owned by the identity application layer."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from backend.app.identity.domain import (
    AccountProvisioningResult,
    AccountStatus,
    AccountStatusAction,
    ActionTokenPurpose,
    ActionTokenRecord,
    AuthSession,
    ConsentAction,
    ConsentFact,
    ConsentScope,
    IdentifierType,
    LoginIdentifier,
    PasswordCredential,
    RefreshTokenRecord,
    RoleAction,
    RoleCode,
    SecurityEvent,
    UserAccount,
    UserRoleFact,
)


class PasswordService(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, encoded: str, password: str) -> bool: ...
    def burn_unknown(self, password: str) -> None: ...


class IdentifierService(Protocol):
    def normalize(self, identifier_type: IdentifierType, value: str) -> str: ...
    def digest(self, normalized: str) -> bytes: ...


class SecretTokenService(Protocol):
    def generate(self) -> str: ...
    def digest(self, token: str) -> bytes: ...


class AccessTokenIssuer(Protocol):
    def issue(self, *, account: UserAccount, roles: frozenset[RoleCode], session_id: UUID) -> tuple[str, int]: ...


class IdentityRepository(Protocol):
    async def provision_reader(
        self, *, display_name: str, identifier_type: IdentifierType,
        identifier_hash: bytes, display_suffix: str, actor_user_id: int,
        activation: ActionTokenRecord, idempotency_key: str,
    ) -> AccountProvisioningResult: ...
    async def find_identifier(self, identifier_type: IdentifierType, identifier_hash: bytes) -> LoginIdentifier | None: ...
    async def get_account(self, user_id: int) -> UserAccount | None: ...
    async def get_credential(self, user_id: int) -> PasswordCredential | None: ...
    async def set_password_and_activate(self, *, user_id: int, credential: PasswordCredential, token_hash: bytes, now: datetime) -> UserAccount: ...
    async def update_login_failure(self, user_id: int, *, now: datetime, lock_seconds: int, threshold: int) -> None: ...
    async def complete_login(self, user_id: int, *, now: datetime) -> UserAccount: ...
    async def effective_roles(self, user_id: int) -> frozenset[RoleCode]: ...
    async def create_session(self, session: AuthSession, refresh: RefreshTokenRecord) -> None: ...
    async def find_refresh(self, token_hash: bytes) -> RefreshTokenRecord | None: ...
    async def get_session(self, session_uuid: UUID) -> AuthSession | None: ...
    async def rotate_refresh(self, *, consumed_uuid: UUID, replacement: RefreshTokenRecord, now: datetime) -> None: ...
    async def revoke_session(self, session_uuid: UUID, *, reason: str, now: datetime) -> None: ...
    async def revoke_user_sessions(self, user_id: int, *, reason: str, now: datetime) -> None: ...
    async def find_action_token(self, token_hash: bytes, purpose: ActionTokenPurpose) -> ActionTokenRecord | None: ...
    async def append_action_token(self, token: ActionTokenRecord) -> None: ...
    async def replace_password(self, *, user_id: int, credential: PasswordCredential, token_hash: bytes | None, now: datetime) -> UserAccount: ...
    async def append_role_fact(self, fact: UserRoleFact) -> tuple[UserAccount, bool]: ...
    async def set_account_status(
        self, *, user_id: int, action: AccountStatusAction, reason_code: str,
        idempotency_key: str, event_uuid: UUID, actor_user_id: int, now: datetime,
    ) -> tuple[UserAccount, bool]: ...
    async def append_consent(self, fact: ConsentFact) -> None: ...
    async def next_consent_version(self, user_id: int, scope: ConsentScope) -> int: ...
    async def effective_consents(self, user_id: int) -> dict[ConsentScope, bool]: ...
    async def append_security_event(self, event: SecurityEvent) -> None: ...


__all__ = [
    "AccessTokenIssuer", "IdentifierService", "IdentityRepository",
    "PasswordService", "SecretTokenService",
]
