"""Versioned framework-independent contracts frozen during G0."""

from .agent import AgentDecision, AgentDispatch, AgentMessage, AgentResult, ArtifactRef
from .enums import (
    AdaptationState,
    AgentActionType,
    AgentMessageStatus,
    AgentResultStatus,
    AvailabilityStatus,
    BehaviorEventType,
    ChannelRunStatus,
    ConfigStatus,
    DeliveryStrategy,
    EvidenceValidatorStatus,
    ExplanationProvider,
    ExplanationLevel,
    FeedbackType,
    IndexBuildStatus,
    IndexOperation,
    IndexStatus,
    IndexTarget,
    IntentType,
    MessageType,
    NegativeReasonCode,
    OutboxStatus,
    OutputType,
    ReadingStage,
    RecallChannel,
    RecallPhase,
    ResourceType,
    ResourceStateType,
    SnapshotMode,
    SnapshotStage,
    TagSource,
    TaskStatus,
    TriggerScene,
)
from .errors import ErrorCode, WarningCode
from .autonomy import (
    AgentAutonomyError,
    AgentRoleProfile,
    ROLE_PROFILES,
    decision_from_dict,
    validate_decision,
    validate_decision_dict,
)
from .policy import (
    ClarificationQuestion,
    InteractionDecision,
    PolicyResult,
    RetrievalChannelPlan,
    RetrievalPlan,
)
from .state import can_transition

__all__ = [
    "AdaptationState",
    "AgentActionType",
    "AgentAutonomyError",
    "AgentDecision",
    "AgentRoleProfile",
    "AgentMessageStatus",
    "AgentDispatch",
    "AgentMessage",
    "AgentResult",
    "AgentResultStatus",
    "ArtifactRef",
    "AvailabilityStatus",
    "BehaviorEventType",
    "ChannelRunStatus",
    "ClarificationQuestion",
    "ConfigStatus",
    "DeliveryStrategy",
    "ErrorCode",
    "EvidenceValidatorStatus",
    "ExplanationLevel",
    "ExplanationProvider",
    "FeedbackType",
    "IndexBuildStatus",
    "IndexOperation",
    "IndexStatus",
    "IndexTarget",
    "IntentType",
    "InteractionDecision",
    "MessageType",
    "NegativeReasonCode",
    "OutboxStatus",
    "OutputType",
    "PolicyResult",
    "ReadingStage",
    "RecallChannel",
    "RecallPhase",
    "ResourceType",
    "ResourceStateType",
    "RetrievalChannelPlan",
    "RetrievalPlan",
    "SnapshotMode",
    "SnapshotStage",
    "TagSource",
    "TaskStatus",
    "TriggerScene",
    "WarningCode",
    "ROLE_PROFILES",
    "decision_from_dict",
    "validate_decision",
    "validate_decision_dict",
    "can_transition",
]
