"""Canonical enums shared by HTTP, Agent, persistence, and experiment contracts."""

from enum import StrEnum


class ResourceType(StrEnum):
    BOOK = "BOOK"
    PAPER = "PAPER"


class TriggerScene(StrEnum):
    HOME = "HOME"
    SEARCH_AFTER = "SEARCH_AFTER"
    RESOURCE_DETAIL = "RESOURCE_DETAIL"
    FEEDBACK_REFRESH = "FEEDBACK_REFRESH"
    EXPLANATION = "EXPLANATION"


class IntentType(StrEnum):
    GENERAL_RECOMMENDATION = "GENERAL_RECOMMENDATION"
    TOPIC_RECOMMENDATION = "TOPIC_RECOMMENDATION"
    PAPER_RECOMMENDATION = "PAPER_RECOMMENDATION"
    BOOK_RECOMMENDATION = "BOOK_RECOMMENDATION"
    BOOKLIST_RECOMMENDATION = "BOOKLIST_RECOMMENDATION"
    READING_PATH_RECOMMENDATION = "READING_PATH_RECOMMENDATION"
    EXPLANATION_REQUEST = "EXPLANATION_REQUEST"
    UNCLEAR = "UNCLEAR"


class ReadingStage(StrEnum):
    BEGINNER = "BEGINNER"
    INTERMEDIATE = "INTERMEDIATE"
    ADVANCED = "ADVANCED"
    RESEARCH = "RESEARCH"


class SnapshotMode(StrEnum):
    MATERIALIZED_CURRENT = "MATERIALIZED_CURRENT"
    REPLAY_AS_OF = "REPLAY_AS_OF"


class SnapshotStage(StrEnum):
    PRE_PLAN = "PRE_PLAN"
    POST_RANK = "POST_RANK"
    POST_RUN = "POST_RUN"


class OutputType(StrEnum):
    PERSONALIZED_FEED = "PERSONALIZED_FEED"
    TOPIC_RESOURCES = "TOPIC_RESOURCES"
    BOOKLIST = "BOOKLIST"
    READING_PATH = "READING_PATH"


class DeliveryStrategy(StrEnum):
    DIRECT = "DIRECT"
    GUIDED = "GUIDED"
    DEGRADED = "DEGRADED"


class ExplanationLevel(StrEnum):
    SUMMARY = "SUMMARY"
    EVIDENCE = "EVIDENCE"
    LIMITED = "LIMITED"


class AdaptationState(StrEnum):
    NORMAL = "NORMAL"
    FEEDBACK_ADJUSTED = "FEEDBACK_ADJUSTED"


class AgentResultStatus(StrEnum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class AgentActionType(StrEnum):
    """Finite local actions an Agent may propose to the Orchestrator.

    These are deliberately not free-form natural-language intentions.  An
    Agent can choose only an action declared by its role profile; the
    Orchestrator remains the sole owner of global task-state transitions.
    """

    RETURN_RESULT = "RETURN_RESULT"
    FALLBACK = "FALLBACK"
    ASK_CLARIFICATION = "ASK_CLARIFICATION"
    READ_PROFILE = "READ_PROFILE"
    PROBE_RESOURCES = "PROBE_RESOURCES"
    PLAN_RECALL = "PLAN_RECALL"
    SELECT_CHANNELS = "SELECT_CHANNELS"
    REQUEST_REPLAN = "REQUEST_REPLAN"
    RENDER_EVIDENCE = "RENDER_EVIDENCE"
    PROPOSE_PROFILE_DELTA = "PROPOSE_PROFILE_DELTA"
    DEGRADE = "DEGRADE"


class TaskStatus(StrEnum):
    CREATED = "CREATED"
    UNDERSTANDING = "UNDERSTANDING"
    PROBING = "PROBING"
    DECIDING = "DECIDING"
    WAITING_CLARIFICATION = "WAITING_CLARIFICATION"
    RECALLING = "RECALLING"
    RANKING = "RANKING"
    REPLANNING = "REPLANNING"
    EXPLAINING = "EXPLAINING"
    PERSISTING = "PERSISTING"
    COMPLETED = "COMPLETED"
    DEGRADED_COMPLETED = "DEGRADED_COMPLETED"
    FAILED = "FAILED"


class MessageType(StrEnum):
    INTENT_RESOLVE = "INTENT.RESOLVE"
    INTENT_RESOLVED = "INTENT.RESOLVED"
    PROFILE_BUILD = "PROFILE.BUILD"
    PROFILE_READY = "PROFILE.READY"
    SEMANTIC_PROBE = "SEMANTIC.PROBE"
    SEMANTIC_PROBE_READY = "SEMANTIC.PROBE_READY"
    POLICY_DECIDE = "POLICY.DECIDE"
    POLICY_DECIDED = "POLICY.DECIDED"
    RECALL_EXECUTE = "RECALL.EXECUTE"
    RECALL_READY = "RECALL.READY"
    RANK_EXECUTE = "RANK.EXECUTE"
    RANK_READY = "RANK.READY"
    RANK_REPLAN_REQUIRED = "RANK.REPLAN_REQUIRED"
    POLICY_REPLAN = "POLICY.REPLAN"
    POLICY_REPLANNED = "POLICY.REPLANNED"
    POLICY_DOWNGRADE = "POLICY.DOWNGRADE"
    POLICY_DOWNGRADED = "POLICY.DOWNGRADED"
    EXPLAIN_EXECUTE = "EXPLAIN.EXECUTE"
    EXPLAIN_READY = "EXPLAIN.READY"
    FEEDBACK_ANALYZE = "FEEDBACK.ANALYZE"
    FEEDBACK_DELTA_PROPOSED = "FEEDBACK.DELTA_PROPOSED"
    PROFILE_APPLY_DELTA = "PROFILE.APPLY_DELTA"
    PROFILE_UPDATED = "PROFILE.UPDATED"


class FeedbackType(StrEnum):
    FAVORITE = "FAVORITE"
    BORROW = "BORROW"
    REJECT = "REJECT"
    NOT_INTERESTED = "NOT_INTERESTED"
    RATE = "RATE"


class NegativeReasonCode(StrEnum):
    TOPIC_NOT_INTERESTED = "TOPIC_NOT_INTERESTED"
    ALREADY_READ = "ALREADY_READ"
    TOO_BASIC = "TOO_BASIC"
    TOO_ADVANCED = "TOO_ADVANCED"
    LOW_QUALITY = "LOW_QUALITY"
    NOT_NOW = "NOT_NOW"
    REPEATED = "REPEATED"
    OTHER = "OTHER"


class AvailabilityStatus(StrEnum):
    AVAILABLE_BORROW = "AVAILABLE_BORROW"
    AVAILABLE_ONLINE = "AVAILABLE_ONLINE"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
    REMOVED = "REMOVED"


class IndexTarget(StrEnum):
    VECTOR = "VECTOR"
    GRAPH = "GRAPH"


class IndexStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    STALE = "STALE"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class IndexBuildStatus(StrEnum):
    PLANNED = "PLANNED"
    BUILDING = "BUILDING"
    READY = "READY"
    FAILED = "FAILED"
    NOT_ACTIVE = "NOT_ACTIVE"


class IndexOperation(StrEnum):
    UPSERT = "UPSERT"
    DEACTIVATE = "DEACTIVATE"
    REBUILD = "REBUILD"


class TagSource(StrEnum):
    HUMAN = "HUMAN"
    RULE = "RULE"
    LLM = "LLM"
    IMPORT = "IMPORT"


class RecallChannel(StrEnum):
    PROFILE = "PROFILE"
    KEYWORD = "KEYWORD"
    VECTOR = "VECTOR"
    GRAPH = "GRAPH"
    TRENDING = "TRENDING"
    FEEDBACK = "FEEDBACK"


class RecallPhase(StrEnum):
    PROBE = "PROBE"
    FULL = "FULL"


class ChannelRunStatus(StrEnum):
    SUCCESS = "SUCCESS"
    SUCCESS_EMPTY = "SUCCESS_EMPTY"
    TIMEOUT = "TIMEOUT"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class BehaviorEventType(StrEnum):
    SEARCH = "SEARCH"
    VIEW_RESOURCE = "VIEW_RESOURCE"
    VIEW_EXPLANATION = "VIEW_EXPLANATION"
    CLICK_RECOMMENDATION = "CLICK_RECOMMENDATION"
    FAVORITE_RESOURCE = "FAVORITE_RESOURCE"
    BORROW_BOOK = "BORROW_BOOK"
    ACCESS_PAPER_FULLTEXT = "ACCESS_PAPER_FULLTEXT"
    RATE_HIGH = "RATE_HIGH"
    RATE_NEUTRAL = "RATE_NEUTRAL"
    RATE_LOW = "RATE_LOW"
    REJECT_RECOMMENDATION = "REJECT_RECOMMENDATION"
    NOT_INTERESTED = "NOT_INTERESTED"
    RECOMMENDATION_IMPRESSION = "RECOMMENDATION_IMPRESSION"


class ResourceStateType(StrEnum):
    READ = "READ"
    FAVORITED = "FAVORITED"
    BORROWED = "BORROWED"
    HIDDEN = "HIDDEN"
    NOT_NOW = "NOT_NOW"
    DUPLICATE_SUPPRESS = "DUPLICATE_SUPPRESS"


class AgentMessageStatus(StrEnum):
    CREATED = "CREATED"
    DISPATCHED = "DISPATCHED"
    HANDLED = "HANDLED"
    FAILED = "FAILED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    DONE = "DONE"
    DEAD = "DEAD"


class ExplanationProvider(StrEnum):
    TEMPLATE = "TEMPLATE"
    MOCK_LLM = "MOCK_LLM"
    EXTERNAL_LLM = "EXTERNAL_LLM"


class EvidenceValidatorStatus(StrEnum):
    PASSED = "PASSED"
    FALLBACK_TEMPLATE = "FALLBACK_TEMPLATE"
    REJECTED = "REJECTED"


class ConfigStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    REJECTED = "REJECTED"
