#!/usr/bin/env python3
"""Apply one explicitly approved formal-reader consent ChangePlan.

The executor is a deliberately narrow forward-only boundary.  It accepts
only the exact plan id/hash generated by
``build_formal_reader_behavior_consent_plan.py`` and performs one login, one
behavior-learning consent grant, and one logout.  It has no migration, seed,
feedback, behavior, Outbox, graph/vector, model, delete, or retry capability.

The consent POST is never retried.  A lost or malformed response is reconciled
with a read-only MySQL snapshot; if the grant cannot be proven, execution
stops and any already-appended facts remain available for a successor plan.
"""

from __future__ import annotations

import argparse
import asyncio
from datetime import UTC, datetime
import hashlib
import json
from pathlib import Path
import re
import stat
import subprocess
from typing import Any, Mapping
from urllib.error import HTTPError, URLError
from urllib.request import HTTPCookieProcessor, ProxyHandler, Request, build_opener
from http.cookiejar import CookieJar

import asyncmy
from jsonschema import Draft202012Validator, FormatChecker

from scripts.build_formal_reader_behavior_consent_plan import (
    CONSENT_ACTION,
    CONSENT_POLICY_VERSION,
    CONSENT_SCOPE,
    CONSENT_SOURCE,
    DEFAULT_API_BASE_URL,
    FORMAL_READER_ID,
    INPUT_PATHS,
    PROJECT_ROOT,
    READER_CREDENTIAL_FILE,
    SCHEMA_PATH,
    canonical,
    connect_runtime,
    database_identity,
    file_sha256,
    read_full_counts,
    read_identity_state,
    read_env,
)


GIT_PATTERN = re.compile(r"^[0-9a-f]{40}$")
HASH_PATTERN = re.compile(r"^[0-9a-f]{64}$")
RUN_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{2,63}$")
EXPECTED_DELTAS = {
    "iam_auth_session": 1,
    "iam_refresh_token": 1,
    "iam_security_event": 2,
    "user_personalization_consent_fact": 1,
}


class AmbiguousRequest(RuntimeError):
    """A request may have reached the API but its response was not received."""


class Client:
    """Small in-memory-cookie HTTP client with explicit no-retry semantics."""

    def __init__(self, base_url: str) -> None:
        self.base_url = base_url.rstrip("/")
        self._jar = CookieJar()
        self._opener = build_opener(ProxyHandler({}), HTTPCookieProcessor(self._jar))

    def request(
        self,
        method: str,
        path: str,
        *,
        payload: Mapping[str, object] | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> tuple[int, dict[str, Any] | None]:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8") if payload is not None else None
        request_headers = {"Accept": "application/json"}
        if body is not None:
            request_headers["Content-Type"] = "application/json"
        request_headers.update(headers or {})
        request = Request(
            self.base_url + path,
            data=body,
            headers=request_headers,
            method=method,
        )
        try:
            with self._opener.open(request, timeout=10) as response:
                raw = response.read()
                status = int(response.status)
        except HTTPError as exc:
            # An HTTP status is an unambiguous response.  The body is parsed
            # only as a public object and is never copied into evidence.
            return int(exc.code), None
        except (URLError, TimeoutError, OSError) as exc:
            raise AmbiguousRequest(f"{method} {path} response was not received") from exc
        if not raw:
            return status, None
        try:
            value = json.loads(raw.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            return status, None
        return status, value if isinstance(value, dict) else None


def _current_commit() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    commit = result.stdout.strip()
    if GIT_PATTERN.fullmatch(commit) is None:
        raise ValueError("current Git commit is invalid")
    return commit


def _require_clean_worktree() -> None:
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    if result.stdout.strip():
        raise ValueError("working tree must be clean before applying the consent plan")


def _load_json(path: Path) -> dict[str, Any]:
    resolved = path.resolve(strict=True)
    if not resolved.is_relative_to(PROJECT_ROOT):
        raise ValueError("plan path must stay inside the repository")
    value = json.loads(resolved.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("ChangePlan must be a JSON object")
    return value


def _precondition(plan: Mapping[str, Any], prefix: str) -> str:
    for value in plan.get("preconditions", []):
        if isinstance(value, str) and value.startswith(prefix):
            return value.removeprefix(prefix)
    raise ValueError(f"ChangePlan is missing {prefix}")


def approved_baseline(plan: Mapping[str, Any]) -> dict[str, Any]:
    value = json.loads(_precondition(plan, "FORMAL_READER_BASELINE="))
    if not isinstance(value, dict):
        raise ValueError("FORMAL_READER_BASELINE must be an object")
    return value


def approved_consent(plan: Mapping[str, Any]) -> dict[str, str]:
    value = json.loads(_precondition(plan, "CONSENT_ACTION="))
    if not isinstance(value, dict) or any(not isinstance(item, str) for item in value.values()):
        raise ValueError("CONSENT_ACTION must contain only string fields")
    expected = {
        "scope": CONSENT_SCOPE,
        "action": CONSENT_ACTION,
        "policy_version": CONSENT_POLICY_VERSION,
        "source": CONSENT_SOURCE,
    }
    if any(value.get(key) != expected_value for key, expected_value in expected.items()):
        raise ValueError("ChangePlan consent action is outside the fixed behavior-learning grant")
    evidence_hash = value.get("evidence_hash", "")
    expected_hash = hashlib.sha256(
        f"{CONSENT_POLICY_VERSION}:{CONSENT_SCOPE}:{CONSENT_ACTION}".encode("utf-8")
    ).hexdigest()
    if evidence_hash != expected_hash:
        raise ValueError("ChangePlan consent evidence hash is invalid")
    return value


def _validate_targets(plan: Mapping[str, Any], baseline: Mapping[str, Any]) -> None:
    targets = plan.get("targets")
    if not isinstance(targets, list) or len(targets) != 8:
        raise ValueError("ChangePlan must contain exactly eight bounded targets")
    identifiers = [str(item.get("identifier", "")) for item in targets if isinstance(item, dict)]
    if len(identifiers) != 8 or len(set(identifiers)) != 8:
        raise ValueError("ChangePlan targets must be unique objects")
    run_id = str(plan.get("request_run_id", ""))
    expected = {
        ".env.stage2-reader-login.local": ("FILE", "READ", 1, 1),
        f"recpro.iam_user_account:user_id={FORMAL_READER_ID}:security-state": ("MYSQL", "UPDATE_STATUS", 1, 1),
        f"recpro.user_effective_personalization_consent_v:user_id={FORMAL_READER_ID}": ("MYSQL", "READ", None, None),
        f"recpro.iam_auth_session:user_id={FORMAL_READER_ID}:new-login": ("MYSQL", "APPEND", None, None),
        f"recpro.iam_refresh_token:user_id={FORMAL_READER_ID}:new-login": ("MYSQL", "APPEND", None, None),
        f"recpro.iam_security_event:formal-reader-consent:{run_id}": ("MYSQL", "APPEND", None, None),
        f"recpro.user_personalization_consent_fact:user_id={FORMAL_READER_ID}:scope={CONSENT_SCOPE}:grant": ("MYSQL", "APPEND", None, None),
        f"artifacts/verification/iam/formal-reader-behavior-consent/{run_id}/acceptance.json": ("FILE", "CREATE", 0, 1),
    }
    if set(identifiers) != set(expected):
        raise ValueError("ChangePlan target allowlist does not match the consent boundary")
    counts = baseline.get("counts")
    if not isinstance(counts, Mapping):
        raise ValueError("baseline counts are missing")
    for item in targets:
        if not isinstance(item, dict):
            raise ValueError("ChangePlan target is not an object")
        identifier = str(item["identifier"])
        kind, operation, before, after = expected[identifier]
        if item.get("kind") != kind or item.get("operation") != operation:
            raise ValueError(f"target operation is outside the allowlist: {identifier}")
        actual_before = int(item.get("expected_before_count", -1))
        actual_after = int(item.get("expected_after_min_count", -1))
        if before is not None and (actual_before, actual_after) != (before, after):
            raise ValueError(f"target count boundary is invalid: {identifier}")
        if identifier.endswith("personalization_consent_v:user_id=10001"):
            expected_rows = sum(1 for _ in baseline.get("identity", {}).get("consents", {}))
            if (actual_before, actual_after) != (expected_rows, expected_rows):
                raise ValueError("consent view target count does not match the frozen baseline")
        for table, delta in EXPECTED_DELTAS.items():
            if f".{table}:" in identifier:
                table_before = int(counts.get(table, -1))
                if (actual_before, actual_after) != (table_before, table_before + delta):
                    raise ValueError(f"append target count does not match baseline: {table}")


def validate_plan(path: Path, *, approved_plan_id: str, approved_plan_hash: str) -> dict[str, Any]:
    plan = _load_json(path)
    Draft202012Validator(
        json.loads(SCHEMA_PATH.read_text(encoding="utf-8")),
        format_checker=FormatChecker(),
    ).validate(plan)
    if plan.get("classification") != "S2_CONTROLLED_UPDATE" or plan.get("mode") != "DRY_RUN":
        raise ValueError("only an S2_CONTROLLED_UPDATE DRY_RUN plan may be applied")
    if plan.get("plan_id") != approved_plan_id or plan.get("plan_hash") != approved_plan_hash:
        raise ValueError("approved plan id/hash does not match the ChangePlan")
    if HASH_PATTERN.fullmatch(approved_plan_hash) is None:
        raise ValueError("approved plan hash is invalid")
    unsigned = dict(plan)
    unsigned.pop("plan_hash", None)
    if hashlib.sha256(canonical(unsigned)).hexdigest() != approved_plan_hash:
        raise ValueError("ChangePlan canonical hash does not match plan_hash")
    if plan.get("git_commit") != _current_commit():
        raise ValueError("approved plan was generated for a different Git commit")
    _require_clean_worktree()
    hashes = plan.get("input_hashes")
    expected_hashes = {item: file_sha256(PROJECT_ROOT / item) for item in sorted(INPUT_PATHS)}
    if hashes != expected_hashes:
        raise ValueError("consent input hash boundary changed after approval")
    safety = {
        "file_deletions": 0,
        "database_physical_deletions": 0,
        "overwrite_existing": False,
        "destructive_capabilities_required": False,
        "counts_must_not_decrease": True,
    }
    if plan.get("safety_assertions") != safety:
        raise ValueError("ChangePlan safety assertions are not zero-destructive")
    if int(plan.get("max_changes", -1)) != sum(EXPECTED_DELTAS.values()):
        raise ValueError("ChangePlan max_changes must equal the five bounded append rows")
    baseline = approved_baseline(plan)
    approved_consent(plan)
    _validate_targets(plan, baseline)
    run_id = str(plan.get("request_run_id", ""))
    if RUN_ID_PATTERN.fullmatch(run_id) is None:
        raise ValueError("ChangePlan request_run_id is invalid")
    return plan


async def read_runtime_state(values: Mapping[str, str]) -> dict[str, Any]:
    connection = await connect_runtime(values)
    try:
        names, counts = await read_full_counts(connection)
        identity = await read_identity_state(connection)
    finally:
        connection.close()
    return {"table_names": names, "counts": counts, "identity": identity}


async def session_status(values: Mapping[str, str], session_uuid: str) -> dict[str, Any]:
    connection = await connect_runtime(values)
    try:
        async with connection.cursor() as cursor:
            await cursor.execute(
                "SELECT user_id, revoked_at, revoke_reason FROM iam_auth_session WHERE session_uuid=%s",
                (session_uuid,),
            )
            session = await cursor.fetchone()
            await cursor.execute(
                "SELECT COUNT(*), SUM(revoked_at IS NOT NULL) FROM iam_refresh_token WHERE session_uuid=%s",
                (session_uuid,),
            )
            token = await cursor.fetchone()
    finally:
        connection.close()
    return {
        "exists": session is not None,
        "user_id": int(session[0]) if session is not None else None,
        "revoked": bool(session is not None and session[1] is not None),
        "revoke_reason": str(session[2]) if session is not None and session[2] is not None else None,
        "refresh_count": int(token[0]) if token is not None else 0,
        "refresh_revoked_count": int(token[1] or 0) if token is not None else 0,
    }


def _read_credentials() -> dict[str, str]:
    path = READER_CREDENTIAL_FILE.resolve(strict=True)
    if stat.S_IMODE(path.stat().st_mode) != 0o600:
        raise ValueError("protected reader credential file must have mode 0600")
    values = read_env(path)
    try:
        user_id = int(values["RECPRO_STAGE2_READER_USER_ID"])
    except (KeyError, ValueError) as exc:
        raise ValueError("protected reader credential user id is invalid") from exc
    if user_id != FORMAL_READER_ID or not values.get("RECPRO_STAGE2_READER_IDENTIFIER") or not values.get("RECPRO_STAGE2_READER_PASSWORD"):
        raise ValueError("protected reader credential file is incomplete")
    if not 10 <= len(values["RECPRO_STAGE2_READER_PASSWORD"]) <= 128:
        raise ValueError("protected reader password is outside the API boundary")
    return values


def _delta(before: Mapping[str, int], after: Mapping[str, int]) -> dict[str, int]:
    return {
        table: int(after.get(table, 0)) - int(before.get(table, 0))
        for table in sorted(set(before) | set(after))
    }


def _evidence_path(run_id: str) -> Path:
    return PROJECT_ROOT / "artifacts" / "verification" / "iam" / "formal-reader-behavior-consent" / run_id / "acceptance.json"


async def apply(
    *,
    plan: Mapping[str, Any],
    values: Mapping[str, str],
    credentials: Mapping[str, str],
    base_url: str,
) -> dict[str, Any]:
    baseline = approved_baseline(plan)
    current_identity = database_identity(values)
    if current_identity != baseline.get("database_identity") or current_identity != plan.get("environment", {}).get("database_identity"):
        raise ValueError("live MySQL identity differs from the approved plan")
    before = await read_runtime_state(values)
    if before["table_names"] != tuple(sorted(baseline.get("counts", {}))):
        raise ValueError("live MySQL table set differs from the approved baseline")
    if before["counts"] != {str(key): int(value) for key, value in baseline["counts"].items()} or before["identity"] != baseline["identity"]:
        raise ValueError("live MySQL identity baseline differs from the approved plan")
    if base_url != baseline.get("api_base_url", DEFAULT_API_BASE_URL):
        raise ValueError("API base URL differs from the approved plan")
    path = _evidence_path(str(plan["request_run_id"])).resolve()
    if path.exists():
        raise FileExistsError("consent evidence path already exists; refusing to overwrite it")

    statuses: dict[str, int] = {}
    phase = "PRECHECK"
    session_uuid: str | None = None
    consent_attempted = False
    consent_reconciled = False
    logout_reconciled = False
    error: dict[str, str] | None = None
    client = Client(base_url)

    try:
        phase = "READINESS"
        status, _ = client.request("GET", "/api/v1/health/ready")
        statuses["readiness"] = status
        if status != 200:
            raise RuntimeError("identity workbench readiness is not healthy")

        phase = "LOGIN"
        status, login = client.request(
            "POST",
            "/api/v1/auth/login",
            payload={
                "identifier_type": "READER_NUMBER",
                "identifier": credentials["RECPRO_STAGE2_READER_IDENTIFIER"],
                "password": credentials["RECPRO_STAGE2_READER_PASSWORD"],
                "device_type": "BROWSER",
            },
        )
        statuses["login"] = status
        if status != 200 or not isinstance(login, dict) or not isinstance(login.get("access_token"), str):
            raise RuntimeError("login did not return a valid access token")
        access = str(login["access_token"])
        user = login.get("user")
        if not isinstance(user, dict) or int(user.get("user_id", 0)) != FORMAL_READER_ID:
            raise RuntimeError("login response did not prove the planned reader identity")

        phase = "AUTH_ME"
        status, me = client.request("GET", "/api/v1/auth/me", headers={"Authorization": f"Bearer {access}"})
        statuses["me"] = status
        if status != 200 or not isinstance(me, dict) or not isinstance(me.get("session_uuid"), str):
            raise RuntimeError("authenticated identity read did not return a session UUID")
        session_uuid = str(me["session_uuid"])
        if int(me.get("user", {}).get("user_id", 0)) != FORMAL_READER_ID:
            raise RuntimeError("authenticated identity read returned the wrong user")

        phase = "CONSENT"
        consent_attempted = True
        try:
            status, consent = client.request(
                "POST",
                "/api/v1/me/personalization-consents",
                payload={
                    "scope": CONSENT_SCOPE,
                    "action": CONSENT_ACTION,
                    "policy_version": CONSENT_POLICY_VERSION,
                    "source": CONSENT_SOURCE,
                },
                headers={"Authorization": f"Bearer {access}"},
            )
            statuses["consent"] = status
        except AmbiguousRequest:
            statuses["consent"] = -1
            status = -1
            consent = None
        if status == 200 and isinstance(consent, dict):
            returned = consent.get("personalization_consents")
            if isinstance(returned, dict) and returned.get(CONSENT_SCOPE) is True:
                pass
            else:
                raise RuntimeError("consent response did not prove BEHAVIOR_LEARNING=true")
        else:
            reconciled = await read_runtime_state(values)
            consent_reconciled = bool(reconciled["identity"]["consents"].get(CONSENT_SCOPE, False))
            if not consent_reconciled:
                raise RuntimeError("consent grant was not proven; no retry was attempted")

        phase = "LOGOUT"
        status, _ = client.request("POST", "/api/v1/auth/logout", headers={"Authorization": f"Bearer {access}"})
        statuses["logout"] = status
        if status != 204:
            state = await session_status(values, session_uuid)
            logout_reconciled = bool(state["revoked"])
            if not logout_reconciled:
                raise RuntimeError("logout was not proven; no retry was attempted")

        phase = "RECONCILE"
        after = await read_runtime_state(values)
        expected_after = dict(before["counts"])
        for table, delta in EXPECTED_DELTAS.items():
            expected_after[table] = int(expected_after[table]) + delta
        if after["counts"] != expected_after:
            raise RuntimeError("database count delta does not match the approved consent boundary")
        if after["identity"]["account"] != before["identity"]["account"] or after["identity"]["roles"] != before["identity"]["roles"]:
            raise RuntimeError("consent run changed account authorization state")
        if not after["identity"]["consents"].get(CONSENT_SCOPE, False):
            raise RuntimeError("post-run effective consent is not true")
        if session_uuid is None:
            raise RuntimeError("session UUID was not retained for logout reconciliation")
        session = await session_status(values, session_uuid)
        if not session["exists"] or not session["revoked"] or session["user_id"] != FORMAL_READER_ID:
            raise RuntimeError("the planned login session was not revoked")
        evidence_status = "PASS"
    except (AmbiguousRequest, RuntimeError, ValueError, asyncmy.errors.Error) as exc:
        error = {"phase": phase, "type": type(exc).__name__, "message": str(exc)}
        try:
            after = await read_runtime_state(values)
        except (OSError, RuntimeError, ValueError, asyncmy.errors.Error) as reconcile_exc:
            # Keep the preflight snapshot when the database itself is
            # temporarily unavailable.  The failure evidence remains honest
            # and a successor plan can perform a fresh reconciliation.
            after = before
            error["reconcile_error"] = type(reconcile_exc).__name__
        evidence_status = "PARTIAL_FAILURE"

    evidence = {
        "schema_version": "formal-reader-behavior-consent-acceptance-v1",
        "status": evidence_status,
        "verified_at": datetime.now(UTC).isoformat(timespec="milliseconds").replace("+00:00", "Z"),
        "plan_id": plan["plan_id"],
        "plan_hash": plan["plan_hash"],
        "run_id": plan["request_run_id"],
        "user_id": FORMAL_READER_ID,
        "consent_scope": CONSENT_SCOPE,
        "consent_attempted_once": consent_attempted,
        "consent_reconciled_by_read": consent_reconciled,
        "logout_reconciled_by_read": logout_reconciled,
        "statuses": statuses,
        "before_counts": before["counts"],
        "after_counts": after["counts"],
        "append_deltas": _delta(before["counts"], after["counts"]),
        "effective_consents_after": after["identity"]["consents"],
        "database_writes": sum(max(0, value) for value in _delta(before["counts"], after["counts"]).values()),
        "identity_posts": 3 if evidence_status == "PASS" else sum(1 for key in statuses if key in {"login", "consent", "logout"}),
        "deepseek_requests": 0,
        "neo4j_writes": 0,
        "chroma_writes": 0,
        "outbox_claims": 0,
        "file_deletions": 0,
        "database_physical_deletions": 0,
        "credentials_logged": 0,
        "tokens_persisted": 0,
    }
    if error is not None:
        evidence["error"] = error
    path.parent.mkdir(parents=True, exist_ok=False)
    path.write_text(json.dumps(evidence, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if evidence_status != "PASS":
        raise RuntimeError(f"consent plan did not complete; evidence retained at {path.relative_to(PROJECT_ROOT)}")
    return evidence | {"evidence_path": path.relative_to(PROJECT_ROOT).as_posix()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--plan", type=Path, required=True)
    parser.add_argument("--plan-id", required=True)
    parser.add_argument("--plan-hash", required=True)
    parser.add_argument("--env-file", type=Path, default=PROJECT_ROOT / ".env.host")
    parser.add_argument("--base-url", default=DEFAULT_API_BASE_URL)
    args = parser.parse_args()
    if not args.apply:
        raise SystemExit("refusing to execute without --apply")
    try:
        plan = validate_plan(args.plan, approved_plan_id=args.plan_id, approved_plan_hash=args.plan_hash)
        values = read_env(args.env_file.resolve(strict=True))
        credentials = _read_credentials()
        evidence = asyncio.run(apply(plan=plan, values=values, credentials=credentials, base_url=args.base_url))
    except (OSError, RuntimeError, ValueError, asyncmy.errors.Error, json.JSONDecodeError) as exc:
        print(f"[FAIL] formal reader consent plan was not applied: {type(exc).__name__}: {exc}")
        return 1
    print(json.dumps({key: value for key, value in evidence.items() if key not in {"before_counts", "after_counts", "effective_consents_after"}}, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
