<script setup lang="ts">
import { computed, onMounted } from "vue";
import type { EChartsCoreOption as EChartsOption } from "echarts/core";
import EChart from "../components/EChart.vue";
import "../charts/registerInsights";
import { useLibraryStore } from "../stores/library";
import { useRecommendationStore } from "../stores/recommendation";
const library = useLibraryStore(); const recommendation = useRecommendationStore();
onMounted(() => void library.loadOverview());
const overviewUnavailable = computed(() => !library.overview && !!library.overviewError);
const colors = ["#2563eb", "#0891b2", "#4f46e5", "#0d9488", "#60a5fa", "#818cf8"];
const category = computed<EChartsOption>(() => ({ tooltip: { trigger: "item", formatter: "{b}<br/>{c} 项" }, series: [{ type: "treemap", roam: false, nodeClick: false, breadcrumb: { show: false }, data: (library.overview?.categories ?? []).map((x, i) => ({ name: x.name, value: x.count, itemStyle: { color: colors[i % colors.length] } })), label: { show: true, formatter: "{b}\n{c} 项", fontSize: 13, lineHeight: 19, overflow: "truncate" }, upperLabel: { show: false }, itemStyle: { borderColor: "#fff", borderWidth: 3, gapWidth: 2, borderRadius: 6 } }] }));
const decades = computed<EChartsOption>(() => ({ tooltip: { trigger: "axis", valueFormatter: (value: unknown) => `${Number(value).toLocaleString("zh-CN")} 册` }, grid: { left: 58, right: 18, top: 22, bottom: 48 }, xAxis: { type: "category", data: (library.overview?.publication_decades ?? []).map(x => `${x.year}s`), axisLabel: { rotate: 28, hideOverlap: true } }, yAxis: { type: "value", name: "册", nameTextStyle: { color: "#64748b" } }, series: [{ type: "bar", data: (library.overview?.publication_decades ?? []).map(x => x.count), itemStyle: { color: "#2563eb", borderRadius: [6,6,0,0] }, barMaxWidth: 34 }] }));
const availabilityNames: Record<string, string> = { AVAILABLE_BORROW: "可借阅", AVAILABLE_ONLINE: "在线可读", REFERENCE_ONLY: "馆内参考", TEMPORARILY_UNAVAILABLE: "暂不可用", REMOVED: "已下架" };
const availabilityTotal = computed(() => (library.overview?.availability ?? []).reduce((sum,item) => sum + item.count, 0));
const availableTotal = computed(() => (library.overview?.availability ?? []).filter((item) => ["AVAILABLE_BORROW","AVAILABLE_ONLINE"].includes(item.name)).reduce((sum,item) => sum + item.count, 0));
const availabilityRate = computed(() => availabilityTotal.value ? Math.round(availableTotal.value / availabilityTotal.value * 100) : 0);
const availability = computed<EChartsOption>(() => ({ title: { text: `${availabilityRate.value}%`, subtext: "可借/在线", left: "center", top: "40%", textStyle: { fontSize: 26, fontWeight: 760 }, subtextStyle: { fontSize: 12 } }, tooltip: { trigger: "item", formatter: "{b}<br/>{c} 项 · {d}%" }, legend: { bottom: 0, type: "scroll" }, series: [{ type: "pie", radius: ["52%", "76%"], center: ["50%","44%"], data: (library.overview?.availability ?? []).map((x, i) => ({ name: availabilityNames[x.name] || x.name, value: x.count, itemStyle: { color: colors[i % colors.length] } })), label: { show: false }, itemStyle: { borderColor: "#fff", borderWidth: 2, borderRadius: 5 } }] }));
const topics = computed<EChartsOption>(() => ({ tooltip: { formatter: (params: any) => `${params.value[3]}<br/>${Number(params.value[2]).toLocaleString("zh-CN")} 项` }, grid: { left: 10, right: 10, top: 10, bottom: 10 }, xAxis: { min: -1.25, max: 1.25, show: false }, yAxis: { min: -1, max: 1, show: false }, series: [{ type: "scatter", symbolSize: (value: number[]) => Math.min(82, 28 + Math.sqrt(value[2] || 1) * 2.6), data: (library.overview?.popular_topics ?? []).map((x, i, all) => { const angle = i / Math.max(1, all.length) * Math.PI * 2; const radius = .32 + (i % 4) * .18; return [Math.cos(angle) * radius, Math.sin(angle) * radius, x.count, x.name]; }), label: { show: true, formatter: (p: any) => p.value[3], color: "#0f172a", fontSize: 12 }, labelLayout: { hideOverlap: true }, itemStyle: { color: (p: any) => colors[p.dataIndex % colors.length], opacity: .72 } }] }));
const channelItems = computed(() => recommendation.items.slice(0, 8));
const channels = computed<EChartsOption>(() => ({ tooltip: { trigger: "axis", axisPointer: { type: "shadow" }, valueFormatter: (value: unknown) => `${Math.round(Number(value) * 100)}%` }, legend: { top: 0 }, grid: { left: 124, right: 18, top: 42, bottom: 26 }, xAxis: { type: "value", max: 1, axisLabel: { formatter: (value: number) => `${Math.round(value * 100)}%` } }, yAxis: { type: "category", data: channelItems.value.map((item) => `#${item.rank_no} ${item.resource.title.length > 10 ? `${item.resource.title.slice(0,10)}…` : item.resource.title}`) }, series: ["MYSQL","GRAPH","VECTOR"].map((channel, index) => ({ name: channel === "GRAPH" ? "Neo4j" : channel === "VECTOR" ? "Chroma" : "MySQL", type: "bar", data: channelItems.value.map((item) => item.evidence?.channel_scores[channel] ?? 0), itemStyle: { color: colors[index] }, barMaxWidth: 14 })) }));
const penalties = computed(() => recommendation.items.map((item) => ({ title: item.resource.title, value: item.evidence?.negative_penalty ?? 0 })).filter((item) => item.value > 0).sort((a,b) => b.value-a.value));
const topTopic = computed(() => library.overview?.popular_topics[0]);
</script>
<template>
  <div class="insights-view"><header class="view-header"><div><span class="eyebrow">COLLECTION INTELLIGENCE</span><h1>馆藏洞察</h1><p>全部图表来自 Exploration 只读接口；不使用预置统计。</p></div><div class="view-header__meta"><span class="data-stamp">数据版本 {{ library.overview?.dataset_version || '读取中' }}</span><button v-if="overviewUnavailable" class="data-retry-button" type="button" @click="library.retryOverview">重新读取馆藏数据</button></div></header>
    <div class="insight-metrics metric-grid"><div class="metric-card"><span>馆藏总量</span><strong>{{ library.overview?.totals.resources.toLocaleString('zh-CN') ?? '—' }}</strong><small>资源总数</small></div><div class="metric-card"><span>图书</span><strong>{{ library.overview?.totals.books.toLocaleString('zh-CN') ?? '—' }}</strong><small>结构化书目</small></div><div class="metric-card"><span>当前可用</span><strong>{{ availableTotal.toLocaleString('zh-CN') }}</strong><small>{{ availabilityRate }}% 可借或在线</small></div><div class="metric-card"><span>知识节点</span><strong>{{ library.overview?.graph.nodes.toLocaleString('zh-CN') ?? '—' }}</strong><small>热门主题：{{ topTopic?.name || '—' }}</small></div></div>
    <div class="insight-grid">
      <section class="insight-card glass-panel is-wide"><div class="mini-panel-title"><span>分类知识版图</span><b>面积表示真实数量 · Top 10</b></div><EChart :option="category" :loading="library.loadingOverview" :empty="!library.overview?.categories.length" :error="library.overviewError" aria-label="馆藏分类矩形树图" /><div class="chart-table"><span v-for="item in library.overview?.categories.slice(0,5)" :key="item.name"><b>{{ item.name }}</b><em>{{ item.count.toLocaleString('zh-CN') }} 项</em></span></div></section>
      <section class="insight-card glass-panel"><div class="mini-panel-title"><span>馆藏可用状态</span><b>{{ availabilityTotal.toLocaleString('zh-CN') }} 项</b></div><EChart :option="availability" :empty="!library.overview?.availability.length" aria-label="馆藏可用状态环形图" /></section>
      <section class="insight-card glass-panel is-wide"><div class="mini-panel-title"><span>出版年代分布</span><b>数量分布，不表示趋势预测</b></div><EChart :option="decades" :empty="!library.overview?.publication_decades.length" aria-label="出版年代数量柱状图" /></section>
      <section class="insight-card glass-panel"><div class="mini-panel-title"><span>热门主题</span><b>气泡面积表示馆藏数量</b></div><EChart :option="topics" :empty="!library.overview?.popular_topics.length" aria-label="热门主题防重叠气泡图" /></section>
      <section class="insight-card glass-panel is-wide"><div class="mini-panel-title"><span>当前推荐三通道分数</span><b>{{ recommendation.items.length ? `${recommendation.items.length} 个真实结果` : '等待推荐' }}</b></div><EChart :option="channels" :empty="!channelItems.length" empty-text="完成一次智能推荐后，将按每本书分别显示 MySQL、Neo4j 与 Chroma 分数。" aria-label="当前推荐结果三通道分组横向条形图" /></section>
      <section class="insight-card glass-panel"><div class="mini-panel-title"><span>负反馈影响</span><b>独立惩罚，不与通道分数相加</b></div><div v-if="penalties.length" class="penalty-ranking"><span v-for="item in penalties" :key="item.title"><b>{{ item.title }}</b><i><em :style="{ width: `${Math.round(item.value*100)}%` }" /></i><strong>−{{ item.value.toFixed(2) }}</strong></span></div><div v-else class="compact-empty"><b>当前无负反馈惩罚</b><span>{{ recommendation.items.length ? '本次结果未受到资源抑制。' : '完成推荐后在此展示真实影响。' }}</span></div></section>
    </div>
  </div>
</template>
